# Site settings
title: Paul Carter
email: pacman128@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the github page of Paul Carter. I'm a software developer
  using mostly C++, Java and Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pacman128.github.io" # the base hostname & protocol for your site
twitter_username: pacman0x80
github_username:  pacman128

# Build settings
markdown: kramdown
